/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorClientes;
import ec.edu.ups.controlador.ControladorFacturas;
import ec.edu.ups.controlador.ControladorSitios;
import ec.edu.ups.controlador.ControladorVehiculos;
import ec.edu.ups.modelo.Clientes;
import ec.edu.ups.modelo.Facturas;
import ec.edu.ups.modelo.Sitioss;

import ec.edu.ups.modelo.Vehiculos;
import java.time.LocalDateTime;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author NANCY
 */
public class VentanaTiketIngresos extends javax.swing.JInternalFrame {

    private ControladorClientes controladorCliente;
    private ControladorVehiculos controladorVehiculo;
    private ControladorSitios controladorSitio;
    private ControladorFacturas controladorFactura;
    private String numero;
    private LocalDateTime local;
    /**
     * Creates new form VentanaTiketIngreso
     * @param controladorFactura
     * @param controladorSitio
     * @param controladorVehiculo
     * @param controladorCliente
     */
    public VentanaTiketIngresos(ControladorFacturas controladorFactura,ControladorSitios controladorSitio,ControladorVehiculos controladorVehiculo,ControladorClientes controladorCliente) {
        initComponents();
        
        this.controladorFactura= controladorFactura;
        this.controladorSitio= controladorSitio;
        this.controladorVehiculo=controladorVehiculo;
        this.controladorCliente= controladorCliente;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    public void CrearFactura(){

        local = LocalDateTime.now();
        String estado="deuda";
        
        Calendar fechaIngreso = Calendar.getInstance();

        Sitioss sitio=this.controladorSitio.buscar(numero);
        System.out.println(sitio);
        Vehiculos vehiculo = sitio.getVehiculos();
        Clientes cliente=vehiculo.getClientes();
        
        Facturas factura=new Facturas(fechaIngreso, estado, cliente, sitio);
        boolean respuesta= controladorFactura.crear(factura);
        
        String datos = "\nFecha y hora de ingreso: "+fechaIngreso.getTime()+"\nCliente: " +cliente.getNombre()+" "+cliente.getApellido()+"\nCedula: "+cliente.getCedula()+"\nPlaca vehiculo: "+vehiculo.getPlaca()+"\nMarca: "+vehiculo.getMarca()+"\nModelo: "+vehiculo.getModelo()+"\nNumero sitio parqueado: "+sitio.getId();
        txtDatos.setText(datos);
        JOptionPane.showMessageDialog(this, "Operación : " + respuesta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDatos = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        txtDatos.setEditable(false);
        txtDatos.setColumns(20);
        txtDatos.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        txtDatos.setRows(5);
        jScrollPane1.setViewportView(txtDatos);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        CrearFactura();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDatos;
    // End of variables declaration//GEN-END:variables
}
