/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorClientes;
import ec.edu.ups.controlador.ControladorContratos;
import ec.edu.ups.controlador.ControladorSitios;
import ec.edu.ups.controlador.ControladorVehiculos;
import ec.edu.ups.modelo.Clientes;
import ec.edu.ups.modelo.Contratos;
import ec.edu.ups.modelo.Sitioss;
import ec.edu.ups.modelo.Vehiculos;
import java.util.Calendar;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;

/**
 *
 * @author NANCY
 */
public class VentanaContratos extends javax.swing.JInternalFrame {

    private ControladorContratos controladorContrato;
    private ControladorClientes controladorCliente;
    private ControladorVehiculos controladorVehiculo;
    private ControladorSitios controladorSitio;
    private VentanaPrincipals ventanaPrincipal;
    private VentanaGestionVehiculos ventanaGestionVehiculo;
    /**
     * Creates new form VentanaContratos
     * @param controladorContrato
     * @param controladorSitio
     * @param controladorVehiculo
     * @param controladorCliente
     * @param ventanaPrincipal
     * @param ventanaGestionVehiculo
     */
    public VentanaContratos(ControladorContratos controladorContrato,ControladorSitios controladorSitio,ControladorVehiculos controladorVehiculo,ControladorClientes controladorCliente , VentanaPrincipals ventanaPrincipal, VentanaGestionVehiculos ventanaGestionVehiculo) {
        initComponents();
        
        this.controladorContrato=controladorContrato;
        this.controladorSitio=controladorSitio;
        this.controladorVehiculo=controladorVehiculo;
        this.controladorCliente= controladorCliente;
        this.ventanaPrincipal=ventanaPrincipal;
        this.ventanaGestionVehiculo=ventanaGestionVehiculo;
    }

    private void limpiar() {
        txtPlaca.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCedula.setText("");
        txtTotal.setText("");
        txtSitio.setText("");
        cbxEstado.setSelectedIndex(0);
        //JDateE.setDateFormatString("");
        JDateS.setDateFormatString("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        btnCrearContrato = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnBuscarContrato = new javax.swing.JButton();
        txtNumero = new javax.swing.JTextField();
        btnTerminarContrato = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnCalcularValor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSitio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        JDateE = new com.toedter.calendar.JDateChooser();
        JDateS = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel11.setText("Borre el numero solo en caso de busqueda del contrato");

        btnCrearContrato.setText("Crear Contrato");
        btnCrearContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearContratoActionPerformed(evt);
            }
        });

        jLabel8.setText("Sitio de Parqueo");

        btnBuscarContrato.setText("Buscar Contrato");
        btnBuscarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarContratoActionPerformed(evt);
            }
        });

        btnTerminarContrato.setText("Terminar Contrato");
        btnTerminarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarContratoActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero de Contrato");

        btnCalcularValor.setText("Calcular valor");
        btnCalcularValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularValorActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha de Entrada");

        jLabel12.setText("Contrato por dia:$ 15 ");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 204));

        jLabel13.setText("Contrato por semana:$ 50 ");

        jLabel4.setText("Fecha de Salida");

        jLabel14.setText("Contrato por mes:$ 90");

        txtApellido.setEditable(false);
        txtApellido.setBackground(new java.awt.Color(255, 255, 204));

        jLabel15.setText("Contratos no superior a un mes ");

        jLabel5.setText("Nombre Cliente");

        txtCedula.setEditable(false);
        txtCedula.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setText("Apellido");

        jLabel1.setText("Placa del vehiculo");

        JDateE.setDateFormatString("y MMM d HH:mm:ss");

        JDateS.setDateFormatString("y MMM d HH:mm:ss");

        jLabel9.setText("Estado");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pagado", "no pagado" }));

        jLabel10.setText("Total a Pagar");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscra Vehiculo");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel7.setText("Cedula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxEstado, 0, 158, Short.MAX_VALUE)
                            .addComponent(txtSitio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombre)
                            .addComponent(txtApellido)
                            .addComponent(txtCedula)
                            .addComponent(txtTotal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnCrearContrato))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscarContrato)
                                .addGap(41, 41, 41)
                                .addComponent(btnTerminarContrato))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JDateS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JDateE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCalcularValor)
                                    .addComponent(btnBuscar)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(32, 32, 32))
                            .addComponent(JDateE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(JDateS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSitio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularValor))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearContrato)
                    .addComponent(btnBuscarContrato)
                    .addComponent(btnTerminarContrato))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearContratoActionPerformed
        boolean resultado = false;
        long codigo=Long.parseLong(txtNumero.getText());
        Calendar fechaEntrada = JDateE.getCalendar();
        Calendar fechaSalida = JDateS.getCalendar();
        String palaca= txtPlaca.getText();
        Vehiculos vehiculo = controladorVehiculo.buscarPlaca(palaca);
        Clientes cliente= vehiculo.getClientes();
        String numero=txtSitio.getText();
        String estado=(String) cbxEstado.getSelectedItem();

        String tv=txtTotal.getText();
        double total=Double.parseDouble(txtTotal.getText());


        if(palaca.isEmpty()||estado.isEmpty()||numero.isEmpty()||tv.isEmpty()){
            JOptionPane.showMessageDialog(this, "Llene todos los campos solicitados");
        }else{
            if(controladorContrato.buscar(codigo)!=null){
                JOptionPane.showMessageDialog(this, "Contrato ya creado con este numero");
            }else{
                Sitioss siti=controladorSitio.buscar(numero);
                if(siti!= null){
                    if(siti.getEstado().equals("Libre")){
                        Sitioss sitio= controladorSitio.buscar(numero);
                        sitio.setEstado("Contrato");
                        sitio.setVehiculos(vehiculo);
                        controladorSitio.actualizar(sitio);
                        if(estado.equals("pagado")){
                            Contratos contrato= new Contratos(codigo, cliente, sitio, fechaEntrada, fechaSalida, estado, 0);
                            controladorContrato.crear(contrato);
                        }else{
                            Contratos contrato= new Contratos(codigo, cliente, sitio, fechaEntrada, fechaSalida, estado, total);
                            controladorContrato.crear(contrato);
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "El sitio indicado esta ocupado");
                    }
                } else {
                    Sitioss sitio = new Sitioss(numero, "Contrato", vehiculo);
                    controladorSitio.crear(sitio);
                    if (estado.equals("pagado")) {
                        Contratos contrato = new Contratos(codigo, cliente, sitio, fechaEntrada, fechaSalida, estado, 0);
                        controladorContrato.crear(contrato);
                    } else {
                        Contratos contrato = new Contratos(codigo, cliente, sitio, fechaEntrada, fechaSalida, estado, total);
                        controladorContrato.crear(contrato);
                    }
                }
            }
            JOptionPane.showMessageDialog(this, "Gracias por adquirir un contrato");
            this.setVisible(false);
            limpiar();

        }
    }//GEN-LAST:event_btnCrearContratoActionPerformed

    private void btnBuscarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarContratoActionPerformed
        long codigo=Long.parseLong(txtNumero.getText());
        Contratos contrato= controladorContrato.buscar(codigo);
        if(contrato!=null){
            JDateE.setCalendar(contrato.getFechaYHoraDeIngreso());
            JDateS.setCalendar(contrato.getFechaYHoraDeSalida());
            Sitioss sitio= contrato.getSitios();
            Vehiculos vehiculo = sitio.getVehiculos();
            txtPlaca.setText(vehiculo.getPlaca());
            txtNombre.setText(contrato.getClientes().getNombre());
            txtApellido.setText(contrato.getClientes().getApellido());
            txtCedula.setText(contrato.getClientes().getCedula());
            txtTotal.setText(String.valueOf(contrato.getTotal()));
            txtSitio.setText(sitio.getId());
            cbxEstado.setSelectedItem(contrato.getEstado());
            btnBuscar.setEnabled(false);
            btnCrearContrato.setEnabled(false);
            btnCalcularValor.setEnabled(false);
            btnTerminarContrato.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(this, "No se  encantrado un contrato con este numero");
        }
    }//GEN-LAST:event_btnBuscarContratoActionPerformed

    private void btnTerminarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarContratoActionPerformed

        long codigo=Long.parseLong(txtNumero.getText());
        Contratos contrato= controladorContrato.buscar(codigo);
        double total=0.0;
        if(contrato.getFechaYHoraDeSalida().before(Calendar.getInstance())){
            if(contrato.getEstado().equals("no pagado")){
                total=contrato.getTotal()+(contrato.getTotal()*0.10);
            }
        }

        txtTotal.setText(String.valueOf(total));
        Clientes cliente = contrato.getClientes();
        Sitioss sitio= contrato.getSitios();

        JOptionPane.showMessageDialog(this, "Gracias vuelva pronto valor a cancelar"+txtTotal.getText());
        Sitioss sitios= controladorSitio.buscar(txtSitio.getText());
        sitios.setEstado("Libre");
        sitios.setVehiculos(null);
        controladorSitio.actualizar(sitios);

        Contratos contrato1 = controladorContrato.buscar(codigo);
        contrato1.setClientes(cliente);
        contrato1.setSitios(sitio);
        contrato1.setFechaYHoraDeIngreso(contrato.getFechaYHoraDeIngreso());
        contrato1.setFechaYHoraDeSalida(contrato.getFechaYHoraDeSalida());
        contrato1.setEstado("pagado");
        contrato1.setTotal(0);
        
        controladorContrato.actualizar(contrato1);

        limpiar();

        btnCrearContrato.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnCalcularValor.setEnabled(true);
        btnTerminarContrato.setEnabled(false);
        this.setVisible(false);
        limpiar();
    }//GEN-LAST:event_btnTerminarContratoActionPerformed

    private void btnCalcularValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularValorActionPerformed
        long DiferenciaMiliSegundos= Math.abs(JDateS.getCalendar().getTimeInMillis()-JDateE.getCalendar().getTimeInMillis());
        long dias=TimeUnit.MILLISECONDS.toDays(DiferenciaMiliSegundos);

        if(dias<=7){
            int valorPagar=(int)(dias*15);
            txtTotal.setText(String.valueOf(valorPagar));
        }else{
            if(dias<=24){
                double numerose= dias/8;
                if(numerose==1.0){
                    int valorPagar=(int)(1*50);
                    txtTotal.setText(String.valueOf(valorPagar));
                }else
                if(numerose<=2.0){
                    int valorPagar=(int)(2*50);
                    txtTotal.setText(String.valueOf(valorPagar));
                }else
                if(numerose<=3.0){
                    int valorPagar=(int)(3*50);
                    txtTotal.setText(String.valueOf(valorPagar));
                }
            }else{
                if(dias<=30.0||dias==31.0){
                    int valorPagar=(int)(1*90);
                    txtTotal.setText(String.valueOf(valorPagar));
                }else{
                    JOptionPane.showMessageDialog(this, "Contratos maximos por un mes");
                    txtTotal.setText("");
                }
            }

        }
        System.out.println(dias);

    }//GEN-LAST:event_btnCalcularValorActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String palaca= txtPlaca.getText();
        Vehiculos vehiculo = controladorVehiculo.buscarPlaca(palaca);
        if(vehiculo!= null){
            Clientes cliente= vehiculo.getClientes();
            txtNombre.setText(cliente.getNombre());
            txtApellido.setText(cliente.getApellido());
            txtCedula.setText(cliente.getCedula());
        }else{
            int opcion=JOptionPane.showConfirmDialog(this, "Vehiculo no encontrado desea crear uno");
            if(opcion== JOptionPane.YES_OPTION)
            {
                ventanaPrincipal.getDesktopPane().add(ventanaGestionVehiculo);
                ventanaGestionVehiculo.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateE;
    private com.toedter.calendar.JDateChooser JDateS;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarContrato;
    private javax.swing.JButton btnCalcularValor;
    private javax.swing.JButton btnCrearContrato;
    private javax.swing.JButton btnTerminarContrato;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtSitio;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
